# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            David Rach
tagline:          ''
description:      ''
url:              https://davidrach.github.io
baseurl:          /

author:
  name:           'David Rach'
  url:            https://davidrach.github.io

plugins: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/davidrach/davidrach.github.io
