project:
  type: website

website:
  google-analytics: "UA-342215677"
  title: "David Rach"
  favicon: "images/Favicon.png"
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
    right:
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: "My Blog"
      - href: publications.qmd
        text: Publications
      - icon: github
        href: https://github.com/DavidRach/
      - icon: twitter
        href: https://twitter.com/DavidRach2
  page-footer: 
   left: Made with [Quarto](https:quartopub.com)
   right: View [Website Code](https://github.com/DavidRach/DavidRach.github.io)

format:
  html:
    css: styles.css

editor: visual

