project:
  type: website
  output-dir: docs
website:
  google-analytics:
    tracking-id: "G-B7X33YDF5P"
  title: "David Rach"
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
    right:
      - href: about.qmd
        text: About
      - text: Research
        menu: 
          - href: courses.qmd
            text: Courses
          - href: publications.qmd
            text: Papers
          - href: talks.qmd
            text: Talks
          - href: research.qmd
            text: Research
          - href: software.qmd
            text: Software
      - href: Resume_2026.pdf
        text: Resume
      - href: posts.qmd
        text: Blog
      - icon: youtube
        href: https://www.youtube.com/@StepUpCytometry
        aria-label: YouTube
      - icon: github
        href: https://github.com/DavidRach/
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: View [Website Code](https://github.com/DavidRach/DavidRach.github.io)

format:
  html:
    css: styles.css

