project:
  type: website

website:
  title: "David Rach"
  navbar:
    background: white
    search: FALSE
    right:
      - href: about.qmd
        text: Home
      - research.qmd
      - publications.qmd
      - service.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/DavidRach/
      - icon: twitter
        href: https://twitter.com/DavidRach2

format:
  html:
    css: styles.css

editor: visual

