project:
  type: website
  output-dir: docs

website:
  google-analytics: "UA-342215677"
  title: "David Rach"
  favicon: "images/Favicon.png"
  navbar:
    background: white
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/DavidRach/
      - icon: twitter
        href: https://twitter.com/DavidRach2
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: View [Website Code](https://github.com/DavidRach/DavidRach.github.io)

format:
  html:
    css: styles.css

editor: visual

