project:
  type: website
  output-dir: docs

website:
  google-analytics: "UA-342215677"
  title: "David Rach"
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
    right:
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
      - href: Research
        menu: 
          - href: abstracts.qmd
            text: Abstracts
      - icon: github
        href: https://github.com/DavidRach/
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: View [Website Code](https://github.com/DavidRach/DavidRach.github.io)

format:
  html:
    css: styles.css

